# Imagem Base
FROM python:3.9

# Pasta de trabalho
WORKDIR /app

# Copiando o script
COPY producer.py /app

# Instalando dependências
RUN pip install kafka-python faker

# Rodando script
CMD ["python", "producer.py"]
